### ISSUE TITLE
Provide development instructions

### ISSUE THREAD

**Issue by fazpu** [yagajs/leaflet-ng2#245]
I am just starting with Angular 4 development. I was unable to set up a development environment - I could not build the examples (see https://github.com/yagajs/leaflet-ng2/issues/244).

It seems a "lib" directory is referenced in package.json, but I did not see any command that would create it.

Also, it would be nice if there could be a webpack solution with watch functionality.

Thank you for the library and the effort!!!

**Comment by atd-schubert** [comment]
As seen in #244 you should not do anything further to build and run the examples. We got also a hint for the script-command `npm run build-examples` in our `README.md`.

For something like a "watch task" you should use a framework that supplies that functionality. I added a hint for that in `README.md` as you can see in the above mentioned commit.

@fazpu do you have any other questions according to the development instructions?

**Comment by atd-schubert** [comment]
Like mentioned in #251 give a hint how to get access the directives to handle them like normal Leaflet classes in the "JavaScript" way.

**Comment by atd-schubert** [comment]
By the way, I was quite happy about the new Leaflet version 1.1.0, because it is not allowed anymore to add plugins on the `L` namespace, but I just read the [release nodes of 1.2.0](http://leafletjs.com/2017/08/08/leaflet-1.2.0.html) and sadly they turn back, but just for compatibility reasons. So it is still not allowed, but still possible:

"Traditionally, Leaflet plugins has altered and added to Leaflet’s namespace (the L global), something which is no longer allowed after Leaflet was rebuilt on ES6 modules (an imported module is read-only). To preserve backwards compatibility, we have made a workaround to make the Leaflet namespace and its contents mutable again."

**Comment by atd-schubert** [comment]
See also #273
