### ISSUE TITLE
Problems with the styling of the map container

### ISSUE THREAD

**Issue by vlados** [yagajs/leaflet-ng2#282]
Hi, 
I've tryed adding the package to an existing application but it's importing the YagaModule without errors and the element is just blank in the page.
Then I've tried creating a new clean project with the steps provided in the documentation, but the same thing happened. I am seeing the map if the css is not loaded https://imgur.com/02eQemG
If I load the leaflet css everything is disappearing https://imgur.com/NAvN9ym
Demo repo: https://github.com/vlados/yaga-map-test/blob/master/src/app/app.component.ts

**Comment by atd-schubert** [comment]
I have to take another look on this. I think there is a a change in the Angular CLI. I normally use it with Ionic and there you have the possibility to do the following in your scss:

```
.yaga-map {
  min-height: 300px;
}
```

The background is that not the `yaga-map` element is the map-root, it is the `div` element below, otherwise you have trouble with the leaflet-styling, because it needs to have a `div` element.

When you add this to your `app.component.css` it also doesn't work, but I don't know why at the moment. The only fix (I know at the moment) is to add the style to your `index.html` directly or into a style you load in your `index.html`.

Try something like this:

```html
<html>
<head>
  <style>
    .yaga-map {
      min-height: 300px;
      /* ... */
    }
  </style>
</head>
<body>
  <!-- ... -->
</body>
</html>
```

On the other hand, there are a lot of people who have problems with that, so I will keep this issue open and try to find a better solution!

**Comment by vlados** [comment]
Then the resolution will be:
```
::ng-deep .yaga-map {
     display: block;
     min-height: 300px;
     border: 2px solid black;
 }
```
in the styling
