### ISSUE TITLE
Is there any way to reload the map dynamically?

### ISSUE THREAD

**Issue by ganigapeta** [yagajs/leaflet-ng2#399]
Hi @atd-schubert, 

Is there any way to reload a map dynamically? actually I am using a re-sizable container once resized map not loading properly(map not fully loading).

**Comment by atd-schubert** [comment]
You will have the same problem with LeafletJS, but they provide [a method in the map class](https://github.com/Leaflet/Leaflet/blob/master/src/map/Map.js#L525) for solving this problem.

In my opinion, the best way to solve your problem is:

* Use the [`angular-resizable-element` directive](https://www.npmjs.com/package/angular-resizable-element) for resizing the map (I don't know this module, but it looks fine at first glance)
* Import your YAGA-map-component as view- or content-child to the parent component of the map. Maybe [this](https://github.com/yagajs/leaflet-ng2#use-standard-leaflet-plugins) will help you out.
* Call the `invalidateSize` method on resize in your parent-component's template:
```html
<yaga-map
    mwlResizable
    (resizeEnd)="mapComponent.invalidateSize()"
>
    <!-- ... -->
</yaga-map>
```

Have fun ;)
